### ISSUE TITLE
appointment status saving as string instead of integer

### ISSUE THREAD

**Issue by shawnorrific** [kstensberg/bizeebird#122]
should be:

0 = Scheduled
1 = Checked In
2 = Checked Out
3 = Cancelled
4 = No Show

**Comment by shawnorrific** [comment]
Do we want it to save as integers like it was before or as strings? Either is probably ok, but technically the column for status on the appointment table is an integer.

**Comment by kstensberg** [comment]
to change it to a string would require a schema change.

it's are also faster to search on, however, the database is unlikely to be large enough for this to matter
